create table shop_crm;

\c shop_crm;

create table users(
  id int generated by default as identity primary key,
  role smallint not null default 0,
  login varchar(40) not null,
  password varchar(64) not null
);
create unique index admin_index on admins(lower(login));
create extension pgcrypto;

create table products(
  id int generated by default as identity primary key,
  barcode varchar(128),
  name text not null,
  description text
);
create unique index barcode_index on products(lower(barcode));

create table product_items (
  id int generated by default as identity primary key,
  product_id int,
  count int not null,
  original_price varchar,
  markup_price varchar not null,
  time timestamp with time zone default current_timestamp,
  CONSTRAINT fk_product
    FOREIGN KEY(product_id)
      REFERENCES products(id)
      ON DELETE SET NULL
);

create table orders(
  id int generated by default as identity primary key,
  time timestamp with time zone default current_timestamp,
  status smallint default 0 not null,
  admin_id int,
  CONSTRAINT fk_admin
    FOREIGN KEY(admin_id) 
      REFERENCES admins(id)
      ON DELETE SET NULL
);

create table order_items(
  id int generated by default as identity primary key,
  order_item_time timestamp with time zone default current_timestamp,
  product_count int,
  product_id int,
  order_id int,
  CONSTRAINT fk_product_item
    FOREIGN KEY(product_id) 
      REFERENCES products(id)
      ON DELETE SET NULL,
  CONSTRAINT fk_order
    FOREIGN KEY(order_id) 
      REFERENCES orders(id)
      ON DELETE SET NULL
);
